### ISSUE TITLE
Presentation/interaction layer for the model

### ISSUE THREAD

**Issue by alchenist** [Data4Democracy/boston-crash-modeling#10]
It's important for both model evaluation (against subject matter expertise) and presentation to the public/planners/engineers to have some kind of way to interact with model predictions. This could be anything from a barebones map to a webmap with more interactivity. This could happen concurrently with model development—we could generate predictions from the benchmark model or use dummy data.

**Comment by bpben** [comment]
@alicefeng has done most of the work here.  The visualization folder contains scripts related to generating visualizations.  We still need additional polish and thought going into these.

**Comment by bpben** [comment]
Closing this now, we have at least a partial solution done.
