### ISSUE TITLE
Plot all segments on a map

### ISSUE THREAD

**Issue by alicefeng** [Data4Democracy/boston-crash-modeling#24]
We currently have around 24,000 individual road and intersection segments in our data which is too much for Leaflet to handle.  It would be nice to find a way to be able to plot all of the segments in one map so that we can create some descriptive visualizations of the features in our dataset.

**Comment by andhint** [comment]
I was able to plot them by using geopandas .plot() method. It took quite a while (~5 min) and looked like a mess but it might be doable with some tweaking

**Comment by alicefeng** [comment]
Nice!  Does geopandas' plotting function make slippy maps?

**Comment by andhint** [comment]
I don't think so, it's basically just a matplotlib plot

**Comment by alicefeng** [comment]
Gotcha.  Yeah we'll want something that allows users to pan around and zoom in/out given the disparity between the size of the map and the level of detail people will want to be able to view it at.

Some very cursory research seems to point toward making our own maptiles but Uber just released a few tutorials on making maps using their own WebGL-based libraries which could be a solution as well: [https://uber-common.github.io/vis-academy/#/](url)

**Comment by bpben** [comment]
@alicefeng this is closed, is that right? Code is contained in the [viz directory](https://github.com/Data4Democracy/boston-crash-modeling/tree/master/src/visualization)

**Comment by bpben** [comment]
@alicefeng this is closed, is that right? Code is contained in the [viz directory](https://github.com/Data4Democracy/boston-crash-modeling/tree/master/src/visualization)

**Comment by alicefeng** [comment]
Haven't actually implemented this but yes, it does look like we've figured out a way to do it via Mapbox
