### ISSUE TITLE
Create standard input / output standards between feature gen / modeling / viz tracks

### ISSUE THREAD

**Issue by therriault** [Data4Democracy/boston-crash-modeling#32]
Early in the project, we identified three distinct project tracks:

1. Feature Generation - taking raw data sources and turning them into features for modeling (also technically includes generating modeling outcomes, but that's a relatively minor part of it that's mostly solved)
1. Modeling - taking prepped outcomes & features and turning them into predictions of crash predictions
1. Visualization - taking models' predictions and translating them into a more useful format (maps, dashboards, reports, etc.)

The three tracks have been going along well, but having a standard format to pass data in between them (passing features/outcomes from #1 to #2 and predictions from #2 to #3) would greatly simplify things, making it so the tracks could operate truly independently.

So the request here is for someone to define exactly what the format should be at the end of stages #1 and #2 with an eye toward how they'll subsequently be used. Some of the questions to answer:

- Where are they stored and in what format?
- How are dates and times handled (both for outcomes and for the features that apply to them, so that we can generate features that are time-variant and readily apply them to specific outcome events)?
- Do we want to put outcomes and features in model-ready format (e.g., # of crashes per week across all permutations of week & segment) or in simplified format (e.g., just the list of crashes, to be reshaped before modeling)?
- How do we arrange the conditions of predictions (e.g., predictions for a given timespan/location)?

Might begin discussion here and or just start writing up standards in a text file or readme---someone should take the first cut and then note here how to edit. Thanks!

**Comment by andhint** [comment]
I just opened a [pull request](https://github.com/Data4Democracy/boston-crash-modeling/pull/35) to answer some of these questions.

**Comment by alicefeng** [comment]
I also created a [Google Doc](https://docs.google.com/document/d/1sm0wqhG0ndfQ5pJQdDBVi2Q-ZQCHcySJKmWt4uVbeDo/edit?usp=sharing) in our Google Drive folder outlining some thoughts.

**Comment by bpben** [comment]
I think this is covered by #68 , #66 #67 #68
