### ISSUE TITLE
Features based on nearby establishments

### ISSUE THREAD

**Issue by alchenist** [Data4Democracy/boston-crash-modeling#6]
First thing that comes to mind is late-night crashes near bars. [Liquor licenses](https://data.boston.gov/dataset/liquor-licenses/resource/aab353c1-c797-4053-a3fc-e893f5ccf547) are open data, although the geocoding may not be perfect.

**Comment by bpben** [comment]
Closing as is too closely related to https://github.com/Data4Democracy/boston-crash-modeling/issues/5
