### ISSUE TITLE
Hooking train/prediction scripts into visualization

### ISSUE THREAD

**Issue by bpben** [Data4Democracy/boston-crash-modeling#74]
Part of the pipeline requires the model to read in processed data and output predictions by week, which can then be passed to the visualization tool to create a dynamic visual.  Right now this will take the form of train_model.py outputting csvs of segment-year-week-prediction, but eventually could be streamlined.

**Comment by terryf82** [comment]
@bpben see https://github.com/Data4Democracy/boston-crash-modeling/issues/67 for some thoughts on recording the temporal attribute of predictions. Is now the time to think about moving to a more capable setup (e.g. the weekly epoch) or is it better to leave that until after the demo release is finished?

**Comment by bpben** [comment]
Updated by #80 : Now have a cleaned/fixed training/prediction script, produces csv which @alicefeng is working on linking into her viz tool.

**Comment by alicefeng** [comment]
Taken care of with #96
