### ISSUE TITLE
March 07 2018

### ISSUE THREAD

**Issue by terryf82** [Data4Democracy/boston-crash-modeling#75]
1. Basic demo of Docker workflow
- How to build the image, or download the image
- How to run the image in a container, with optional volume mounting of external directory
- How to make changes to the image's environment via the Dockerfile

**Comment by terryf82** [comment]
Discuss Demo Release
- goals
- tasks
- timeline

**Comment by bpben** [comment]
Modelling:
Fixed error with crash lags
Almost finished with predictions by week
